# Day 04 - Data Cleaning

## Objective
Check data quality before starting the analysis.

In [5]:
import pandas as pd

df = pd.read_excel("C:/Data Projects/Ecommerce_Sales_Analysis/Data/Superstore.xlsx")

### Missing Values

- No missing values were found in the dataset.

In [6]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

### Duplicate Rows

- No duplicate rows were detected.

In [7]:
df.duplicated().sum()

0

### Data Types

- All columns have appropriate data types.
- Date columns (`Order Date` and `Ship Date`) are correctly stored as **datetime**.

In [11]:
df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

### Negative Profit

- 1,871 rows contain negative profit.
- These records were **not removed** because they represent real business losses rather than data errors.

In [15]:
negative_profit = df[df["Profit"] < 0]

negative_profit

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,0.444,2,0.00,-6599.9780
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",0.556,3,0.00,-3839.9904
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,0.836,2,0.00,-3701.8928
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,0.852,5,0.45,-3399.9800
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,0.876,2,0.20,-2929.4845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1866,1867,CA-2017-118857,2017-04-15,2017-04-18,First Class,AH-10075,Adam Hart,Corporate,United States,Henderson,...,89015,West,FUR-FU-10004460,Furniture,Furnishings,"Howard Miller 12"" Round Wall Clock",12.960,5,0.00,-0.3444
1867,1868,CA-2015-127110,2015-06-25,2015-07-01,Standard Class,CH-12070,Cathy Hwang,Home Office,United States,Philadelphia,...,19143,East,OFF-PA-10003309,Office Supplies,Paper,Xerox 211,12.960,6,0.20,-0.3398
1868,1869,CA-2015-127110,2015-06-25,2015-07-01,Standard Class,CH-12070,Cathy Hwang,Home Office,United States,Philadelphia,...,19143,East,OFF-ST-10002554,Office Supplies,Storage,Tennsco Industrial Shelving,12.960,2,0.20,-0.2685
1869,1870,CA-2016-148201,2016-08-26,2016-08-29,Second Class,CC-12145,Charles Crestani,Consumer,United States,Seattle,...,98103,West,OFF-PA-10000019,Office Supplies,Paper,Xerox 1931,12.960,1,0.00,-0.2098
1870,1871,CA-2014-116932,2014-07-21,2014-07-25,Standard Class,ME-18010,Michelle Ellison,Corporate,United States,San Francisco,...,94122,West,OFF-AR-10002067,Office Supplies,Art,Newell 334,12.960,5,0.00,-0.0895

In [13]:
(df["Profit"] < 0).sum()

1871

In [16]:
df["Profit"].min()

-6599.978

In [17]:
negative_profit[
    ["Order ID", "Product Name", "Sales", "Discount", "Profit"]
]

,Order ID,Product Name,Sales,Discount,Profit
0,CA-2016-152156,Bush Somerset Collection Bookcase,0.444,0.00,-6599.9780
1,CA-2016-152156,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",0.556,0.00,-3839.9904
2,CA-2016-138688,Self-Adhesive Address Labels for Typewriters b...,0.836,0.00,-3701.8928
3,US-2015-108966,Bretford CR4500 Series Slim Rectangular Table,0.852,0.45,-3399.9800
4,US-2015-108966,Eldon Fold 'N Roll Cart System,0.876,0.20,-2929.4845
...,...,...,...,...,...
1866,CA-2017-118857,"Howard Miller 12"" Round Wall Clock",12.960,0.00,-0.3444
1867,CA-2015-127110,Xerox 211,12.960,0.20,-0.3398
1868,CA-2015-127110,Tennsco Industrial Shelving,12.960,0.20,-0.2685
1869,CA-2016-148201,Xerox 1931,12.960,0.00,-0.2098
1870,CA-2014-116932,Newell 334,12.960,0.00,-0.0895

In [18]:
negative_profit = df[df["Profit"] < 0]

negative_profit.shape

(1871, 21)

In [19]:
df[["Sales", "Profit"]].describe()

              Sales       Profit
count   9994.000000  9994.000000
mean     229.858001    28.656896
std      623.245101   234.260108
min        0.444000 -6599.978000
25%       17.280000     1.728750
50%       54.490000     8.666500
75%      209.940000    29.364000
max    22638.480000  8399.976000

### Duplicate Order IDs

- Duplicate Order IDs are expected because a single order can contain multiple products.
- Therefore, they are not considered duplicates in terms of data quality.

In [ ]:
df["Order ID"].duplicated().sum()

## Data Quality Checks

## Key Findings

- The dataset is clean and contains no missing values.
- No duplicate rows exist.
- Data types are correctly assigned.
- Negative profits are valid business records.
- The dataset is ready for exploratory data analysis (EDA).

---

## Skills Learned

- Detecting missing values using `isnull()`.
- Identifying duplicate rows using `duplicated()`.
- Reviewing data types using `dtypes`.
- Summarizing numerical data using `describe()`.
- Distinguishing between data errors and valid business scenarios.
- Performing a basic data quality assessment before analysis.

---

## Conclusion

The dataset passed all major data quality checks and does not require additional cleaning. It is ready for exploratory data analysis in the next stage.